# Generated by Django 4.2.11 on 2024-04-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_support', '0005_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN-PROGRESS', 'In-Progress'), ('CLOSED', 'Closed')], default='Open', max_length=15),
        ),
    ]
